CREATE TABLE  "FEE_STUDENT" 
   ("ROLLNO" INT, 
	"NAME" VARCHAR(55), 
	"EMAIL" VARCHAR(55), 
	"SEX" VARCHAR(55), 
	"COURSE" VARCHAR(55), 
	"FEE" INT, 
	"PAID" INT, 
	"DUE" INT, 
	"ADDRESS" VARCHAR(100), 
	"CONTACT" VARCHAR(55), 
	 CONSTRAINT "FEE_STUDENT_PK" PRIMARY KEY ("ROLLNO") ENABLE
   )
/

CREATE TABLE  "FEE_ACCOUNTANT" 
   (	"ID"  INT, 
	"NAME" VARCHAR(55), 
	"EMAIL" VARCHAR(55), 
	"PASSWORD" VARCHAR(55), 
	"ADDRESS" VARCHAR(55), 
	"CONTACT" VARCHAR(55), 
	 CONSTRAINT "FEE_ACCOUNTANT_PK" PRIMARY KEY ("ID") ENABLE
   )
/